Kode pendamping tulisan https://basangdata.com/pandas-baca-tulis-file-excel

Sumber data:
<ul>
    <li><a href="https://community.tableau.com/docs/DOC-1236">https://community.tableau.com/docs/DOC-1236</a></li>
    <li><a href="https://community.tableau.com/docs/DOC-10174">https://community.tableau.com/docs/DOC-10174</a></li>
</ul>

# Install Paket dibutuhkan

In [18]:
#!pip install xlrd
#!pip install openpyxl

Processing /Users/aansubarkah/Library/Caches/pip/wheels/5b/c0/e7/e16d3916984addf40bd021fa98d1624cb24a9adc48da4e62b5/openpyxl-3.0.3-py2.py3-none-any.whl
Collecting jdcal
  Using cached jdcal-1.4.1-py2.py3-none-any.whl (9.5 kB)
Processing /Users/aansubarkah/Library/Caches/pip/wheels/e2/bd/55/048b4fd505716c4c298f42ee02dffd9496bb6d212b266c7f31/et_xmlfile-1.0.1-py3-none-any.whl
Installing collected packages: jdcal, et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.0.1 jdcal-1.4.1 openpyxl-3.0.3

# Mengimpor pandas

In [1]:
import pandas as pd

# Baca Excel

In [4]:
superstore = pd.read_excel('Sample - Superstore.xls')

In [5]:
superstore

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [6]:
returns = pd.read_excel('Sample - Superstore.xls', sheet_name='Returns')

In [7]:
returns

    Returned        Order ID
0        Yes  CA-2017-153822
1        Yes  CA-2017-129707
2        Yes  CA-2014-152345
3        Yes  CA-2015-156440
4        Yes  US-2017-155999
..       ...             ...
291      Yes  CA-2015-101910
292      Yes  CA-2017-156958
293      Yes  CA-2016-105585
294      Yes  CA-2016-148796
295      Yes  CA-2015-149636

[296 rows x 2 columns]

central = pd.read_excel('Central_Superstore.xlsx')

In [9]:
central

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,7981,CA-2011-103800,2013-01-03,2013-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,740,CA-2011-112326,2013-01-04,2013-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
2,741,CA-2011-112326,2013-01-04,2013-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
3,742,CA-2011-112326,2013-01-04,2013-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
4,7661,CA-2011-105417,2013-01-07,2013-01-12,Standard Class,VS-21820,Vivek Sundaresam,Consumer,United States,Huntsville,...,77340,Central,FUR-FU-10004864,Furniture,Furnishings,"Howard Miller 14-1/2"" Diameter Chrome Round Wa...",76.728,3,0.6,-53.7096
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2318,6822,CA-2014-163860,2016-12-28,2017-01-01,Standard Class,LO-17170,Lori Olson,Corporate,United States,Peoria,...,61604,Central,FUR-FU-10001935,Furniture,Furnishings,3M Hangers With Command Adhesive,2.960,2,0.6,-1.4060
2319,7485,CA-2014-135111,2016-12-28,2017-01-02,Standard Class,CS-12400,Christopher Schild,Home Office,United States,Fargo,...,58103,Central,OFF-AR-10004707,Office Supplies,Art,Staples in misc. colors,2.480,1,0.0,0.8680
2320,7486,CA-2014-135111,2016-12-28,2017-01-02,Standard Class,CS-12400,Christopher Schild,Home Office,United States,Fargo,...,58103,Central,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,25.900,5,0.0,12.6910
2321,4240,CA-2014-158673,2016-12-29,2017-01-04,Standard Class,KB-16600,Ken Brennan,Corporate,United States,Grand Rapids,...,49505,Central,OFF-PA-10000994,Office Supplies,Paper,Xerox 1915,209.700,2,0.0,100.6560
2322,646,CA-2014-126221,2016-12-30,2017-01-05,Standard Class,CC-12430,Chuck Clark,Home Office,United States,Columbus,...,47201,Central,OFF-AP-10002457,Office Supplies,Appliances,Eureka The Boss Plus 12-Amp Hard Box Upright V...,209.300,2,0.0,56.5110

# Menambahkan Satu Kolom

In [10]:
superstore.head(1).T

                                               0
Row ID                                         1
Order ID                          CA-2016-152156
Order Date                   2016-11-08 00:00:00
Ship Date                    2016-11-11 00:00:00
Ship Mode                           Second Class
Customer ID                             CG-12520
Customer Name                        Claire Gute
Segment                                 Consumer
Country                            United States
City                                   Henderson
State                                   Kentucky
Postal Code                                42420
Region                                     South
Product ID                       FUR-BO-10001798
Category                               Furniture
Sub-Category                           Bookcases
Product Name   Bush Somerset Collection Bookcase
Sales                                     261.96
Quantity                                       2
Discount                                       0
Profit                                   41.9136

In [14]:
fullname = superstore['Customer Name'].str.split(' ', n = 1, expand = True)
superstore['First Customer Name'] = fullname[0]

In [15]:
superstore.head(1).T

                                                     0
Row ID                                               1
Order ID                                CA-2016-152156
Order Date                         2016-11-08 00:00:00
Ship Date                          2016-11-11 00:00:00
Ship Mode                                 Second Class
Customer ID                                   CG-12520
Customer Name                              Claire Gute
Segment                                       Consumer
Country                                  United States
City                                         Henderson
State                                         Kentucky
Postal Code                                      42420
Region                                           South
Product ID                             FUR-BO-10001798
Category                                     Furniture
Sub-Category                                 Bookcases
Product Name         Bush Somerset Collection Bookcase
Sales                                           261.96
Quantity                                             2
Discount                                             0
Profit                                         41.9136
First Customer Name                             Claire

In [16]:
superstore[['Customer Name', 'First Customer Name']]

         Customer Name First Customer Name
0          Claire Gute              Claire
1          Claire Gute              Claire
2      Darrin Van Huff              Darrin
3       Sean O'Donnell                Sean
4       Sean O'Donnell                Sean
...                ...                 ...
9989  Tom Boeckenhauer                 Tom
9990       Dave Brooks                Dave
9991       Dave Brooks                Dave
9992       Dave Brooks                Dave
9993      Chris Cortes               Chris

[9994 rows x 2 columns]

# Menyimpan Berkas Baru

In [19]:
superstore.to_excel('superstore.xlsx')